version: "3"
services:
  concerto-ui:
    image: concerto-ui:v1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
    - BACKEND_URI=http://remy-trompier.ch:8123
    ports:
      - 4200:4200
    deploy:
        replicas: 1