version: "3"
services:
  comprenhension-front:
    image: comprenhension-front:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
    - BACKEND_URI=http://remy-trompier.ch:8123
    ports:
      - 8124:4200
    deploy:
        replicas: 1